### ISSUE TITLE
Trying to 

### ISSUE THREAD

**Issue by onny** [hwstar/Buspirate-python3-i2c#1]
Hey, I'm trying to write an simple example code based on your lib. Here's what I do on the bus pirate (which seems to work)

```
onny@onny $ minicom -b 115200 -8 -D /dev/ttyUSB0
HiZ>m3

(danach hardware oder software modus?)

Set speed:
 1. ~5KHz
 2. ~50KHz
 3. ~100KHz
 4. ~400KHz

(1)>3
Ready
I2C>W
Power supplies ON
I2C>P
Pull-up resistors ON
I2C>(1)
Searching I2C address space. Found devices at:
0x16(0x0B W) 0x17(0x0B R) 
I2C>[0x16 0x10 [0x17 r:2]
I2C START BIT
WRITE: 0x16 ACK 
WRITE: 0x10 ACK 
I2C START BIT
WRITE: 0x17 ACK 
READ: 0x5F  ACK 0x17 
NACK
I2C STOP BIT
```

Here's my python code:

```
from I2C import *

writeaddr = 0x16
readaddr = 0x17
command = 0x0f # remCap

i2c = I2C("/dev/buspirate", 115200)

if i2c.BBmode():
    pass
else:
    fatalError("Can't set binmode on Buspirate!")

if i2c.enter_I2C():
    pass
else:
    fatalError("Can't set raw mode on Buspirate!")

if not i2c.cfg_pins(I2CPins.POWER | I2CPins.PULLUPS):
    fatalError("Failed to set I2C peripherals on BusPirate!")

if not i2c.set_speed(I2CSpeed._50KHZ):
    fatalError("Can't set I2C speed on Buspirate!")

i2c.timeout(0.2)

# send
i2c.send_start_bit()
stat = i2c.bulk_trans(2, [writeaddr << 1, command])
i2c.send_stop_bit()
if stat[0] == chr(0x01):
    raise IOError("I2C write command on address 0x%02x not acknowledged!" % (writeaddr))

# read
result = b''
i2c.send_start_bit()
stat = i2c.bulk_trans(1, [readaddr << 1 | 1])
if stat[0] == chr(0x01):
    raise IOError("I2C read command on address 0x%02x not acknowledged!" % (readaddr))
command = ord(i2c.read_byte())
i2c.send_ack()
length = ord(i2c.read_byte())
i2c.send_ack()
count = 0
while(length):
    result = result + i2c.read_byte()
    count += 1
    if(count == length):
        i2c.send_nack()
        break
    else:
        i2c.send_ack()
i2c.send_stop_bit()
print(result)
```

Unfortunately I'll only get several 0xff as response :(

Best regards,
Jonas

**Comment by hwstar** [comment]
I have a hunch as to what might be going on.
Hi Jonas,
1. Using the serial interface and terminal program, you are sending the commands at human speed. 
2. When you are writing the command in the script, you issue a read right after sending the command. This may violate the timing of the device you are communicating with (Especially if it is a microprocessor such as the Arduino)

I would try adding a ridiculous delay (like 100mSec) right after the write and before the read to see if that makes a difference.

**Comment by onny** [comment]
Thanks, I've managed to get it working after debugging it with a digital analyzer. Here's my current script using your ported library: https://gist.github.com/onny/c059c84917362e132baa
Thats really cool!

**Comment by hwstar** [comment]
Great!

Is that battery controller some kind of product in a box or is it an integrated circuit? Looks interesting.

**Comment by onny** [comment]
@hwstar: These kind of controllers speak SMBUS protocol over I2C and you can find them in every laptop battery. Pinout is of course different.
